language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install -n --dev --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
  - vendor/bin/coveralls -v